<div class="spacer"></div>
<div class="reservation_table">
    <div class="nav">
        <button id="date-prev"><</button>
        <input type="date" id="date">
        <button id="date-next">></button>
    </div>
    <table id="reservation-table">
    </table>
</div>

<form id="order-form" action="">

    <label for="reservations">Rezervace:</label>
    <div id="reservations">
        <!-- <input disabled type="number" name="lane-number" value="1">
        <input disabled type="date" name="start-date">
        <input disabled type="date" name="end-date">
        <br>
        <input disabled type="number" name="lane-number" value="1">
        <input disabled type="date" name="start-date">
        <input disabled type="date" name="end-date"> -->
    </div>

</form>

<script src="js/reservations.js"></script>