<div class="spacer"></div>
<div class="reservation_table">
    <div class="nav">
        <button id="date-prev">
            < </button>
                <input type="date" id="date">
                <button id="date-next"> > </button>
    </div>
    <table id="reservation-table">
    </table>
    <button id="confirm">Confirm Selection</button>
</div>

<form method="post" id="order-form">

    <div id="reservations">
    </div>
    <input type="submit" value="Submit Order" id="reservation-submit" enctype="multipart/form-data">

</form>
<script src="js/reservations.js"></script>