<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC app I3B S1 23/24</title>
</head>
<body>
    <ul>
        <li><a href="index">Úvod</a></li>
        <li><a href="login">Login</a></li>
        <li><a href="logout">lougout</a></li>
    </ul>


    <?php
        $this->controller->showView();
    ?>


    <?php foreach ($messages as $message) { 
        echo "zpravy";
    ?>

        <div class="zprava">
            <?= $message["text"]?>
        </div>

    <?php } ?>

</body>
</html>