<!DOCTYPE html>
<html lang="cs">

<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="css/nav.css"> -->
    <?php foreach ($this->controller->css as $css): ?>
        <link rel="stylesheet" href="<?= $css ?>">
    <?php endforeach; ?>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <script src="js/Nav.js"></script>
    <title>Bowling Jadran</title>
</head>

<body>
    <nav class='navbar exNavbar'>
        <img id="logo" src="storage/Logo.PNG" alt="">
        <h1>Restaurace & Pivnice Jadran</h1>
        <ul>
            <li>
                <a href="login">
                    <?php echo ($this->loggedUser == false) ? "login" : $this->loggedUser["username"] ?>
                </a>
            </li>
            <li><a href="createReservation">Rezervovat</a></li>
            <li><a href="index">Úvod</a></li>
        </ul>
    </nav>

    <div class="navBG navBGcon"></div>
    <?php
    $this->controller->showView();
    ?>

    <?php foreach ($messages as $message): ?>
        <div class="zprava">
            <?= $message["text"] ?>
        </div>
    <?php endforeach; ?>

</body>

</html>