<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC app I3B S1 23/24</title>
</head>
<body>
    <ul>
        <li><a href="index">Úvod</a></li>
        <li><a href="lanes">Dráhy</a></li>
        <li><a href="reservations">Rezervace</a></li>
        <li><a href="login">Přihlášení</a></li>
        <li><a href="logout">Odhlášení</a></li>
        <li><a href="register">Registrace</a></li>
    </ul>

    <?php
        $this->controller->showView();
    ?>

    <?php foreach ($messages as $message): ?>
        <div class="zprava">
            <?= $message["text"] ?>
        </div>
    <?php endforeach; ?>

</body>
</html>
