<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>

</head>
<body>
    <h1>Login</h1>

<form method="post">
    <div>
        <label for="login">Login</label>
        <input type="text" name="login" id="login" required>
    </div>
    <div>
        <label for="heslo">Heslo</label>
        <input type="password" name="heslo" id="heslo" required>
    </div>
   
    <input type="submit" value="Přihlásit se">
 </form>
</body>
</html>