<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrace</title>
</head>
<body>
    <?php if(isset($_SESSION["user"]) && $id_user_type == 1): ?>
        <h1>Registrace nového admina</h1>
    <?php else: ?>
        <h1>Registrace</h1>
    <?php endif; ?>

    <form method="post">
        <div>
            <label for="username">Uživatelské jméno</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div>
            <label for="password">Heslo</label>
            <input type="password" name="password" id="password" required>
        </div>
        <div>
            <label for="confirm_password">Heslo znovu</label>
            <input type="password" name="confirm_password" id="confirm_password" required>
        </div>
        <input type="submit" value="Registrovat se">
    </form>
</body>
</html>
