

<h1>Reservations</h1>
<input type="date" name="SetDate" id="SetDate">
<table class="ReserveTable">
      <caption>Seznam předmětů</caption>
       <thead>
         <tr>     

         </tr>
       </thead>
       <tbody>
         <tr>

         </tr>
         <tr>

         </tr>
         <tr>

         </tr>
         <tr>
           <td>TEV</td>
           <td>Tělesná výchova</td>
           <td>KOA</td>
         </tr>
       </tbody>
     </table>

<ul>
<?php foreach ($reservations as $reservation) { ?>

    <li>
        <?php
            echo "id: ". $reservation->id;
            echo "<br>";
            echo "typ rezervace: ( id -> ". $reservation->type. " )";
            echo "<br>";
            echo "cislo drahy: ". $reservation->lane->id ;
            echo "<br>";
            echo "začátek rezervace: ". $reservation->startDate;
            echo "<br>";
            echo "konec rezervace: ". $reservation->endDate;
        ?>

    </li>
<?php } ?>

<h1>Overlaping reservations</h1>
<?php foreach ($overlapingReservations as $reservation) { ?>

<li>
    <?php
        echo "id: ". $reservation->id;
        echo "<br>";
        echo "typ rezervace: ( id -> ". $reservation->type. " )";
        echo "<br>";
        echo "cislo drahy: ". $reservation->lane->id ;
        echo "<br>";
        echo "začátek rezervace: ". $reservation->startDate;
        echo "<br>";
        echo "konec rezervace: ". $reservation->endDate;
    ?>

</li>
<?php } ?>

</ul>